baseurl = "https://www.dray.id.au/"
languageCode = "en-us"
theme = "hugo-uno"
title = "Justin Dray"
author = "Justin Dray"
copyright = ""
builddrafts = false

[indexes]
    category = "categories"
    tag = "tags"

[Params]
    AuthorName = "Justin Dray"
    disqus = "justindray"
    email = "justin@dray.id.au"
    github = "justin8"
    twitter = "justindray"
    description = "Tech ramblings"
    linkedin = "justindray"
    cover = "/images/cover.jpg"
    #logo = "/images/logo.jpg"


